themes:
  - id: green
    name: 绿色主题
    emoji: ??
    keywords:
      - 绿色经济
      - 绿色金融
      - 碳
      - 污
      - 绿色发展
      - 碳中和
      - 碳达峰
      - 低碳
      - 碳排放
      - 环境污染
      - 可持续发展
      - 绿色创新
      - 可再生能源
      - 生态

  - id: digital
    name: 数字主题
    emoji: ??
    keywords:
      - 数字经济
      - 数字化
      - 数实
      - 数智
      - 实数
      - 人工智能
      - 大数据
      - 区块链
      - 数字化转型
      - 数字金融
      - 互联网
      - 智能制造
      - 平台经济
      - 算法
